-- ============================================================
-- Historial de múltiples entradas por cerveza (beer_tastings).
--
-- user_beers sigue siendo la fila-resumen por (user_id, beer_id) que
-- ya alimenta logros/rankings/rachas/retos — NO cambia su forma
-- (sigue una fila por cerveza). beer_tastings es la bitácora nueva:
-- cada vez que el usuario "carga una cata" (primera vez o repetida)
-- se inserta una fila acá, y un trigger sincroniza los campos
-- representativos (foto/nota/rating/ubicación más recientes) hacia
-- user_beers para que la tarjeta única de Mi Cuaderno siga
-- funcionando sin cambios.
--
-- XP: la PRIMERA cata de una cerveza gana la fórmula completa de
-- siempre (10 base + 15/20/25 + 10 combo + 20 coleccionable). Cada
-- cata siguiente de la MISMA cerveza gana +3 fijo. Se computa una
-- sola vez al INSERT de beer_tastings y nunca se recalcula en un
-- UPDATE (evita farmear editando). user_beers."XP" pasa a ser la
-- suma de beer_tastings.xp_earned, mantenida por triggers en cascada
-- en vez del viejo modelo "recalcular todo en cada guardado".
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 1. Tabla + backfill (antes de crear ningún trigger, para que el
-- backfill copie el XP ya existente tal cual, sin que ningún trigger
-- lo recalcule ni lo duplique).
-- ────────────────────────────────────────────────────────────
CREATE TABLE public.beer_tastings (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          uuid NOT NULL,
  beer_id          bigint NOT NULL,
  rating           numeric,
  comment          text,
  user_photo_url   text,
  photo_hash       bigint,
  location_lat     double precision,
  location_lng     double precision,
  location_name    text,
  location_public  boolean NOT NULL DEFAULT true,
  price_paid       numeric,
  xp_earned        int NOT NULL DEFAULT 0,
  created_at       timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (user_id, beer_id) REFERENCES public.user_beers(user_id, beer_id) ON DELETE CASCADE,
  CONSTRAINT beer_tastings_comment_length CHECK (comment IS NULL OR length(comment) <= 500),
  CONSTRAINT beer_tastings_rating_check CHECK (rating IS NULL OR (rating BETWEEN 1 AND 5 AND (rating * 2) = floor(rating * 2))),
  CONSTRAINT beer_tastings_price_range CHECK (price_paid IS NULL OR (price_paid > 0 AND price_paid <= 200))
);

CREATE INDEX beer_tastings_user_beer_idx ON public.beer_tastings (user_id, beer_id, created_at DESC);

-- Cada user_beers existente se vuelve la "primera cata" de su
-- historial — mismo XP, mismo created_at, no se recalcula nada.
INSERT INTO public.beer_tastings (
  user_id, beer_id, rating, comment, user_photo_url, photo_hash,
  location_lat, location_lng, location_name, location_public, price_paid,
  xp_earned, created_at
)
SELECT
  user_id, beer_id, "Rating", NULLIF(comment, ''), user_photo_url, photo_hash,
  location_lat, location_lng, location_name, COALESCE(location_public, true), price_paid,
  COALESCE("XP", 0), COALESCE(created_at, now())
FROM public.user_beers;

ALTER TABLE public.beer_tastings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "select_own_tastings" ON public.beer_tastings
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "insert_own_tastings" ON public.beer_tastings
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "update_own_tastings" ON public.beer_tastings
  FOR UPDATE TO authenticated USING (user_id = auth.uid());

-- ────────────────────────────────────────────────────────────
-- 2. XP de cada cata: fórmula completa si es la primera, +3 fijo si
-- ya hay catas previas para esa (user_id, beer_id). Nunca confía en
-- lo que mande el cliente. Inmutable en UPDATE (lock_tasting_xp).
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.compute_tasting_xp()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
DECLARE
  base_xp       int := 10;
  bonus_xp      int := 0;
  has_rating    boolean;
  has_comment   boolean;
  has_photo     boolean;
  beer_rareza   text;
  beer_especial boolean;
  v_prior_count int;
BEGIN
  SELECT count(*) INTO v_prior_count
  FROM public.beer_tastings
  WHERE user_id = NEW.user_id AND beer_id = NEW.beer_id;

  IF v_prior_count = 0 THEN
    has_rating  := NEW.rating IS NOT NULL AND NEW.rating > 0;
    has_comment := NEW.comment IS NOT NULL AND length(trim(NEW.comment)) > 0;
    has_photo   := NEW.user_photo_url IS NOT NULL AND length(trim(NEW.user_photo_url)) > 0;

    IF has_rating  THEN base_xp := base_xp + 15; END IF;
    IF has_comment THEN base_xp := base_xp + 20; END IF;
    IF has_photo   THEN base_xp := base_xp + 25; END IF;
    IF has_rating AND has_comment AND has_photo THEN base_xp := base_xp + 10; END IF;

    SELECT rareza, es_edicion_especial INTO beer_rareza, beer_especial
    FROM public.beers_new WHERE id = NEW.beer_id;

    IF beer_especial IS TRUE OR beer_rareza IN ('rara', 'epica', 'legendaria', 'mitica') THEN
      bonus_xp := 20;
    END IF;

    NEW.xp_earned := base_xp + bonus_xp;
  ELSE
    NEW.xp_earned := 3;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_compute_tasting_xp ON public.beer_tastings;
CREATE TRIGGER trg_compute_tasting_xp
  BEFORE INSERT ON public.beer_tastings
  FOR EACH ROW EXECUTE FUNCTION public.compute_tasting_xp();

CREATE OR REPLACE FUNCTION public.lock_tasting_xp()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  NEW.xp_earned := OLD.xp_earned; -- editar una cata (typo en la nota, etc.) nunca cambia el XP ya ganado
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_lock_tasting_xp ON public.beer_tastings;
CREATE TRIGGER trg_lock_tasting_xp
  BEFORE UPDATE ON public.beer_tastings
  FOR EACH ROW EXECUTE FUNCTION public.lock_tasting_xp();

-- ────────────────────────────────────────────────────────────
-- 3. Cascada hacia user_beers: XP acumulado + campos representativos
-- (la tarjeta única de Mi Cuaderno sigue mostrando "la más reciente").
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.sync_user_beers_from_tasting()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.user_beers SET
      "XP"             = "XP" + NEW.xp_earned,
      "Rating"         = NEW.rating,
      comment          = COALESCE(NEW.comment, ''),
      user_photo_url   = NEW.user_photo_url,
      photo_hash       = NEW.photo_hash,
      location_lat     = NEW.location_lat,
      location_lng     = NEW.location_lng,
      location_name    = NEW.location_name,
      location_public  = NEW.location_public,
      price_paid       = NEW.price_paid
    WHERE user_id = NEW.user_id AND beer_id = NEW.beer_id;
  ELSIF TG_OP = 'UPDATE' THEN
    -- Solo si esta cata sigue siendo la más reciente actualizamos la
    -- representativa — editar una cata vieja del historial no debe
    -- pisar lo que se muestra en la tarjeta principal. Se compara por
    -- id (monótono) y no por created_at: dentro de una misma
    -- transacción now() devuelve el mismo valor para todos los
    -- INSERTs, así que dos catas cargadas juntas podrían empatar en
    -- timestamp.
    IF NEW.id = (
      SELECT MAX(id) FROM public.beer_tastings
      WHERE user_id = NEW.user_id AND beer_id = NEW.beer_id
    ) THEN
      UPDATE public.user_beers SET
        "Rating"         = NEW.rating,
        comment          = COALESCE(NEW.comment, ''),
        user_photo_url   = NEW.user_photo_url,
        photo_hash       = NEW.photo_hash,
        location_lat     = NEW.location_lat,
        location_lng     = NEW.location_lng,
        location_name    = NEW.location_name,
        location_public  = NEW.location_public,
        price_paid       = NEW.price_paid
      WHERE user_id = NEW.user_id AND beer_id = NEW.beer_id;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_user_beers_from_tasting ON public.beer_tastings;
CREATE TRIGGER trg_sync_user_beers_from_tasting
  AFTER INSERT OR UPDATE ON public.beer_tastings
  FOR EACH ROW EXECUTE FUNCTION public.sync_user_beers_from_tasting();

-- ────────────────────────────────────────────────────────────
-- 4. user_beers."XP" pasa a ser un total gestionado exclusivamente
-- por la cascada de arriba. En INSERT arranca en 0 (la primera cata,
-- insertada a continuación por el mismo flujo de guardado, lo sube al
-- valor real). En UPDATE directo (cliente o edición de la
-- representativa) el total queda protegido: pg_trigger_depth() > 1
-- identifica que el UPDATE viene de la cascada interna de
-- beer_tastings (la única fuente legítima de cambios de XP); a nivel
-- superior (depth <= 1, cualquier UPDATE directo del cliente o RPC)
-- el total existente se preserva sin importar qué mande el payload.
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.compute_user_beers_xp()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  IF NEW."Rating" IS NOT NULL
     AND (NEW."Rating" < 1 OR NEW."Rating" > 5 OR (NEW."Rating" * 2) <> floor(NEW."Rating" * 2)) THEN
    RAISE EXCEPTION 'Rating inválido: debe ser NULL o un valor entre 1 y 5 en pasos de 0.5';
  END IF;

  IF TG_OP = 'INSERT' THEN
    NEW."XP" := 0;
  ELSIF pg_trigger_depth() <= 1 THEN
    NEW."XP" := OLD."XP";
  END IF;

  RETURN NEW;
END;
$$;

-- (el trigger trg_compute_user_beers_xp ya existe apuntando a esta
-- función — CREATE OR REPLACE alcanza, no hace falta recrearlo)

-- ────────────────────────────────────────────────────────────
-- 5. entry_flags: nueva columna para referenciar la cata puntual.
-- ────────────────────────────────────────────────────────────
ALTER TABLE public.entry_flags ADD COLUMN IF NOT EXISTS tasting_id bigint REFERENCES public.beer_tastings(id) ON DELETE SET NULL;

-- Vincula los flags automáticos ya existentes con la cata backfillada
-- correspondiente, para no perder la referencia.
UPDATE public.entry_flags ef
SET tasting_id = bt.id
FROM public.beer_tastings bt
WHERE bt.user_id = ef.user_id AND bt.beer_id = ef.beer_id
  AND ef.source IN ('duplicate_photo', 'velocity')
  AND ef.tasting_id IS NULL;

DROP INDEX IF EXISTS public.entry_flags_auto_unique;
CREATE UNIQUE INDEX entry_flags_auto_unique
  ON public.entry_flags (tasting_id, source)
  WHERE source IN ('duplicate_photo', 'velocity') AND tasting_id IS NOT NULL;

-- ────────────────────────────────────────────────────────────
-- 6. Anti-trampa: se muda de user_beers a beer_tastings — ahora cada
-- fila SÍ representa un evento real de carga, cosa que ya no es
-- cierto para user_beers una vez que existen catas repetidas.
-- ────────────────────────────────────────────────────────────
DROP TRIGGER IF EXISTS trg_check_photo_flags ON public.user_beers;

CREATE OR REPLACE FUNCTION public.check_photo_flags()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
DECLARE
  v_dup_beer_id bigint;
  v_dup_distance int;
  v_recent_count int;
BEGIN
  IF NEW.photo_hash IS NOT NULL THEN
    SELECT beer_id, bit_count((photo_hash # NEW.photo_hash)::bit(64))
      INTO v_dup_beer_id, v_dup_distance
    FROM public.beer_tastings
    WHERE user_id = NEW.user_id
      AND beer_id <> NEW.beer_id
      AND photo_hash IS NOT NULL
      AND bit_count((photo_hash # NEW.photo_hash)::bit(64)) <= 5
    ORDER BY bit_count((photo_hash # NEW.photo_hash)::bit(64))
    LIMIT 1;

    IF v_dup_beer_id IS NOT NULL THEN
      INSERT INTO public.entry_flags (user_id, beer_id, tasting_id, source, reason)
      VALUES (
        NEW.user_id, NEW.beer_id, NEW.id, 'duplicate_photo',
        format('Foto casi idéntica (distancia %s/64) a la usada en beer_id=%s', v_dup_distance, v_dup_beer_id)
      )
      ON CONFLICT (tasting_id, source) WHERE source IN ('duplicate_photo', 'velocity') AND tasting_id IS NOT NULL
      DO UPDATE SET reason = EXCLUDED.reason, created_at = now(), status = 'pending';
    END IF;
  END IF;

  SELECT count(*) INTO v_recent_count
  FROM public.beer_tastings
  WHERE user_id = NEW.user_id
    AND user_photo_url IS NOT NULL
    AND created_at >= now() - interval '1 hour';

  IF v_recent_count > 10 THEN
    INSERT INTO public.entry_flags (user_id, beer_id, tasting_id, source, reason)
    VALUES (
      NEW.user_id, NEW.beer_id, NEW.id, 'velocity',
      format('%s entradas verificadas en la última hora', v_recent_count)
    )
    ON CONFLICT (tasting_id, source) WHERE source IN ('duplicate_photo', 'velocity') AND tasting_id IS NOT NULL
    DO UPDATE SET reason = EXCLUDED.reason, created_at = now(), status = 'pending';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_check_photo_flags_tastings ON public.beer_tastings;
CREATE TRIGGER trg_check_photo_flags_tastings
  AFTER INSERT ON public.beer_tastings
  FOR EACH ROW
  WHEN (NEW.user_photo_url IS NOT NULL)
  EXECUTE FUNCTION public.check_photo_flags();

-- ────────────────────────────────────────────────────────────
-- 7. admin_unverify_entry: si el flag referencia una cata puntual,
-- limpiar esa cata (y, si además es la representativa vigente,
-- limpiar también user_beers para que la tarjeta principal lo refleje
-- al toque). Si no tiene tasting_id (reporte comunitario, sigue
-- apuntando solo a la fila representativa), mismo comportamiento de
-- siempre.
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_unverify_entry(p_flag_id uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
DECLARE
  v_user_id uuid;
  v_beer_id bigint;
  v_tasting_id bigint;
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION 'No autorizado';
  END IF;

  SELECT user_id, beer_id, tasting_id INTO v_user_id, v_beer_id, v_tasting_id
  FROM public.entry_flags WHERE id = p_flag_id;

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Reporte no encontrado';
  END IF;

  IF v_tasting_id IS NOT NULL THEN
    UPDATE public.beer_tastings SET user_photo_url = NULL, photo_hash = NULL WHERE id = v_tasting_id;
  END IF;

  UPDATE public.user_beers
  SET user_photo_url = NULL, photo_hash = NULL
  WHERE user_id = v_user_id AND beer_id = v_beer_id;

  UPDATE public.entry_flags
  SET status = 'confirmed', reviewed_at = now(), reviewed_by = auth.uid()
  WHERE id = p_flag_id;
END;
$$;
