-- ============================================================
-- Colección de Copas comunitaria — mismo espíritu que la Pokédex
-- de cervezas (beers_new / beer_suggestions / user_beers), tres
-- tablas espejo:
--   glass_suggestions → beer_suggestions
--   glasses           → beers_new (catálogo aprobado, con rareza)
--   user_glasses      → user_beers (colección personal, con foto
--                        de verificación propia)
-- ============================================================

-- ── glasses: catálogo aprobado ──────────────────────────────
CREATE TABLE public.glasses (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre               text NOT NULL,
  marca                text,
  descripcion          text,
  foto_url             text,
  beer_id              bigint REFERENCES public.beers_new(id) ON DELETE SET NULL,
  rareza               text NOT NULL DEFAULT 'comun'
                         CHECK (rareza IN ('comun','poco_comun','rara','epica','legendaria','mitica')),
  sugerida_por_user_id uuid REFERENCES public.profiles(id),
  sugerida_por_nombre  text,
  created_at           timestamptz DEFAULT now()
);

ALTER TABLE public.glasses ENABLE ROW LEVEL SECURITY;

CREATE POLICY glasses_allow_anon_read ON public.glasses
  FOR SELECT TO anon USING (true);
CREATE POLICY glasses_allow_authenticated_read ON public.glasses
  FOR SELECT TO authenticated USING (true);
CREATE POLICY glasses_admin_insert ON public.glasses
  FOR INSERT TO public WITH CHECK (is_admin());
CREATE POLICY glasses_admin_update ON public.glasses
  FOR UPDATE TO public USING (is_admin()) WITH CHECK (is_admin());

-- ── glass_suggestions: sugerencias pendientes de revisión ───
CREATE TABLE public.glass_suggestions (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  nombre        text NOT NULL CHECK (char_length(trim(nombre)) BETWEEN 1 AND 100),
  marca         text CHECK (marca IS NULL OR char_length(marca) <= 100),
  descripcion   text CHECK (descripcion IS NULL OR char_length(descripcion) <= 500),
  foto_url      text NOT NULL,
  beer_id       bigint REFERENCES public.beers_new(id) ON DELETE SET NULL,
  status        text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  created_at    timestamptz DEFAULT now(),
  reviewed_at   timestamptz,
  reviewed_by   uuid REFERENCES public.profiles(id)
);

ALTER TABLE public.glass_suggestions ENABLE ROW LEVEL SECURITY;

CREATE POLICY gs_insert ON public.glass_suggestions
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY gs_select ON public.glass_suggestions
  FOR SELECT TO authenticated USING (user_id = auth.uid() OR is_admin());
CREATE POLICY gs_update ON public.glass_suggestions
  FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- ── user_glasses: colección personal (foto propia = verificación) ──
CREATE TABLE public.user_glasses (
  user_id        uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  glass_id       bigint NOT NULL REFERENCES public.glasses(id) ON DELETE CASCADE,
  user_photo_url text NOT NULL,
  photo_hash     bigint,
  created_at     timestamptz DEFAULT now(),
  PRIMARY KEY (user_id, glass_id)
);

ALTER TABLE public.user_glasses ENABLE ROW LEVEL SECURITY;

CREATE POLICY ug_select ON public.user_glasses
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY ug_insert ON public.user_glasses
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY ug_update ON public.user_glasses
  FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY ug_delete ON public.user_glasses
  FOR DELETE TO authenticated USING (user_id = auth.uid());

-- ── RPCs: aprobar / rechazar sugerencia (mismo patrón que beer_suggestions) ──
-- approve_glass_suggestion recibe la rareza porque, a diferencia de
-- beers_new, no hay un panel de "editar copa" separado donde el admin
-- pueda tocarla después — se elige en el momento de aprobar.
CREATE FUNCTION public.approve_glass_suggestion(p_suggestion_id uuid, p_rareza text DEFAULT 'comun')
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_s    glass_suggestions%ROWTYPE;
  v_name TEXT;
  v_id   BIGINT;
BEGIN
  IF NOT is_admin() THEN RAISE EXCEPTION 'No autorizado'; END IF;
  IF p_rareza NOT IN ('comun','poco_comun','rara','epica','legendaria','mitica') THEN
    RAISE EXCEPTION 'Rareza inválida';
  END IF;

  SELECT * INTO v_s FROM glass_suggestions
  WHERE id = p_suggestion_id AND status = 'pending';
  IF NOT FOUND THEN RAISE EXCEPTION 'Sugerencia no encontrada o ya revisada'; END IF;

  SELECT nombre INTO v_name FROM profiles WHERE id = v_s.user_id;

  INSERT INTO glasses (nombre, marca, descripcion, foto_url, beer_id, rareza, sugerida_por_user_id, sugerida_por_nombre)
  VALUES (v_s.nombre, v_s.marca, v_s.descripcion, v_s.foto_url, v_s.beer_id, p_rareza, v_s.user_id, v_name)
  RETURNING id INTO v_id;

  UPDATE glass_suggestions
  SET status = 'approved', reviewed_at = now(), reviewed_by = auth.uid()
  WHERE id = p_suggestion_id;

  RETURN v_id;
END;
$$;

CREATE FUNCTION public.reject_glass_suggestion(p_suggestion_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  IF NOT is_admin() THEN RAISE EXCEPTION 'No autorizado'; END IF;

  UPDATE glass_suggestions
  SET status = 'rejected', reviewed_at = now(), reviewed_by = auth.uid()
  WHERE id = p_suggestion_id AND status = 'pending';
END;
$$;

-- Hardening explícito de anon desde el día uno (ver migración
-- 20260801000000_harden_anon_execute_grants.sql): el proyecto tiene
-- default privileges que le dan EXECUTE a anon directamente en cada
-- función nueva, sin pasar por PUBLIC — no alcanza con revocar de
-- PUBLIC solamente.
REVOKE EXECUTE ON FUNCTION public.approve_glass_suggestion(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.approve_glass_suggestion(uuid, text) FROM anon;
GRANT EXECUTE ON FUNCTION public.approve_glass_suggestion(uuid, text) TO authenticated;

REVOKE EXECUTE ON FUNCTION public.reject_glass_suggestion(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.reject_glass_suggestion(uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.reject_glass_suggestion(uuid) TO authenticated;

-- ── Storage: bucket user-glasses (mismo patrón que user-beers) ──
-- Se reutiliza también para la foto de referencia de la sugerencia
-- (prefijo distinto dentro de la misma carpeta del usuario), evitando
-- un bucket aparte solo para eso.
INSERT INTO storage.buckets (id, name, public)
VALUES ('user-glasses', 'user-glasses', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY user_glasses_public_read ON storage.objects
  FOR SELECT USING (bucket_id = 'user-glasses');
CREATE POLICY user_glasses_own_insert ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'user-glasses' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY user_glasses_own_update ON storage.objects
  FOR UPDATE USING (bucket_id = 'user-glasses' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY user_glasses_own_delete ON storage.objects
  FOR DELETE USING (bucket_id = 'user-glasses' AND (storage.foldername(name))[1] = auth.uid()::text);
