-- ============================================================
-- Top Tier personal: ranking manual de cervezas favoritas, un Top
-- "global" + tops por familia de estilo (Lager/IPA/Stout/...), visible
-- en el perfil respetando la misma privacidad que el resto de stats.
--
-- category = 'global' o una de las STYLE_KEYWORDS que ya usa el
-- Catálogo (Dashboard.js) para sus chips de filtro por estilo — no se
-- valida contra beers_new.estilo acá (es texto libre y muy específico
-- por cerveza, ej. "Ale – Belgian Abbey Ale (Blonde)"); el frontend es
-- quien arma la lista de categorías ofrecidas a partir de esas
-- keywords, la RPC solo garantiza que las cervezas sean tuyas.
-- ============================================================

CREATE TABLE public.user_top_beers (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  beer_id     bigint NOT NULL,
  category      text NOT NULL DEFAULT 'global' CHECK (char_length(category) BETWEEN 1 AND 40),
  rank_position smallint NOT NULL CHECK (rank_position BETWEEN 1 AND 10),
  created_at    timestamptz DEFAULT now(),
  FOREIGN KEY (user_id, beer_id) REFERENCES public.user_beers(user_id, beer_id) ON DELETE CASCADE,
  UNIQUE (user_id, category, beer_id)
);

ALTER TABLE public.user_top_beers ENABLE ROW LEVEL SECURITY;

-- Solo lectura directa de tus propias filas (para tu propia UI de
-- edición); la lectura del Top de OTRO usuario pasa por la RPC
-- get_user_top_beers (respeta perfil_publico/amigos). Los writes
-- pasan únicamente por set_top_beers — no hay policy de INSERT/UPDATE/
-- DELETE a propósito, para no permitir tocar la tabla sin pasar por
-- las validaciones de la RPC.
CREATE POLICY utb_select_own ON public.user_top_beers
  FOR SELECT TO authenticated USING (user_id = auth.uid());

-- ── set_top_beers: reemplaza la lista completa de una categoría de una
-- sola vez — agregar, sacar y reordenar son la misma operación, así el
-- cliente simplemente manda el array en el orden final tras soltar el
-- drag & drop. Evita el problema de mover posiciones incrementalmente
-- contra un UNIQUE(position). ──────────────────────────────────────
CREATE FUNCTION public.set_top_beers(p_category text, p_beer_ids bigint[])
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_owned_count int;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'No autenticado';
  END IF;

  IF p_category IS NULL OR char_length(p_category) NOT BETWEEN 1 AND 40 THEN
    RAISE EXCEPTION 'Categoría inválida';
  END IF;

  IF array_length(p_beer_ids, 1) IS NULL THEN
    -- lista vacía = vaciar esa categoría
    DELETE FROM public.user_top_beers WHERE user_id = auth.uid() AND category = p_category;
    RETURN;
  END IF;

  IF array_length(p_beer_ids, 1) > 10 THEN
    RAISE EXCEPTION 'Máximo 10 cervezas por categoría';
  END IF;

  IF array_length(p_beer_ids, 1) != (SELECT COUNT(DISTINCT x) FROM unnest(p_beer_ids) x) THEN
    RAISE EXCEPTION 'No se puede repetir la misma cerveza en la lista';
  END IF;

  SELECT COUNT(*) INTO v_owned_count
  FROM public.user_beers
  WHERE user_id = auth.uid() AND beer_id = ANY(p_beer_ids);

  IF v_owned_count != array_length(p_beer_ids, 1) THEN
    RAISE EXCEPTION 'Solo podés rankear cervezas de tu cuaderno';
  END IF;

  DELETE FROM public.user_top_beers WHERE user_id = auth.uid() AND category = p_category;

  INSERT INTO public.user_top_beers (user_id, beer_id, category, rank_position)
  SELECT auth.uid(), beer_id, p_category, ord
  FROM unnest(p_beer_ids) WITH ORDINALITY AS t(beer_id, ord);
END;
$$;

-- ── get_user_top_beers: mismo patrón de visibilidad que
-- get_visible_user_beers (self / perfil público / amigo). ──────────
CREATE FUNCTION public.get_user_top_beers(p_user_id uuid)
RETURNS TABLE (
  category      text,
  rank_position smallint,
  beer_id       bigint,
  nombre      text,
  foto_url    text,
  estilo      text,
  pais        text,
  rareza      text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT utb.category, utb.rank_position, utb.beer_id, bn.nombre, bn.foto_url, bn.estilo, bn.pais, bn.rareza
  FROM public.user_top_beers utb
  JOIN public.beers_new bn ON bn.id = utb.beer_id
  WHERE utb.user_id = p_user_id
    AND (
      auth.uid() = p_user_id
      OR COALESCE((SELECT perfil_publico FROM public.profiles WHERE id = p_user_id), true) IS TRUE
      OR EXISTS (
        SELECT 1 FROM public.friendships
        WHERE user_id = auth.uid() AND friend_id = p_user_id
      )
    )
  ORDER BY (utb.category != 'global'), utb.category, utb.rank_position;
$$;

-- Hardening explícito de anon desde el día uno (mismo criterio que
-- toda función nueva de acá en adelante, ver 20260801000000).
REVOKE EXECUTE ON FUNCTION public.set_top_beers(text, bigint[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.set_top_beers(text, bigint[]) FROM anon;
GRANT EXECUTE ON FUNCTION public.set_top_beers(text, bigint[]) TO authenticated;

REVOKE EXECUTE ON FUNCTION public.get_user_top_beers(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_user_top_beers(uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.get_user_top_beers(uuid) TO authenticated;
